REMOTE_URL = "http://127.0.0.1:4723/wd/hub"
PLATFORM_NAME = "Android"
PLATFORM_VERSION = "9"
DEVICE_NAME = "9d22273f"
AUTOMATION_NAME = "UiAutomator1"
APP_PACKAGE = "com.android.chrome"
APP_ACTIVITY = "org.chromium.chrome.browser.document.ChromeLauncherActivity"
USE_NEW_WDA= "true"