SONATA_LOGO="//android.view.View[@text='Header Logo']"
ACCEPT_COOKIES="//android.widget.Button[@text='ACCEPT']"
TITLE_0= "//android.view.View[@text='Sonata Services']"
TEXT_0= "//android.view.View[@text='A Technology and Solutions Partner that provides experienced, certified, and dedicated augmented teams to assist you by increasing your bandwidth, and decreasing your time to market']"
TITLE_1= "//android.view.View[@text='Create the Right Team at the Right Time']"
TEXT_1= "//android.view.View[@text='Our experienced teams have 10+ years helping companies to build, deploy, secure, and support critical path products in compliant and non-compliant environments']"
BANNER_0= "//android.widget.Button[@text='item 0']"
BANNER_1= "//android.widget.Button[@text='item 1']"
BANNER_2= "//android.widget.Button[@text='item 2']"
BANNER_3= "//android.widget.Button[@text='item 3']"
ACCELERATE_GROWTH = "//android.view.View[@text='We help you accelerate growth']"
OUR_SERVICES_EXPERTISE = "//android.view.View[@text='Create the most efficient engineering team with Sonata Services. We provide our partners self-managed, cross-functional teams, fully capable of building top-quality products and services for our partners.']"
BRANDS = "//android.widget.Image[@text='company logos' and @index='18']"
SIDE_BAR = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View/android.view.View[1]/android.view.View[1]"
SERVICES_LINK = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View/android.view.View[1]/android.widget.ListView/android.view.View[2]"
SUCCESS_STORIES_LINK = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View/android.view.View[1]/android.widget.ListView/android.view.View[3]"
CAREERS_LINK = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View/android.view.View[1]/android.widget.ListView/android.view.View[4]"
ABOUT_US_LINK = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View/android.view.View[1]/android.widget.ListView/android.view.View[5]"
BLOG_LINK = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View/android.view.View[1]/android.widget.ListView/android.view.View[6]"
CONTACT_LINK = "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.widget.FrameLayout[1]/android.widget.FrameLayout[2]/android.webkit.WebView/android.view.View/android.view.View[1]/android.widget.ListView/android.view.View[7]"
FOOTER = "//android.view.View[@text='Copyright Sonata Services 2018-2020. All Rights Reserved.']"